### ISSUE TITLE
viaccess 0500 ECM not being sent

### ISSUE THREAD

**Issue by barhom** [gfto/tsdecrypt#14]
Started with "-X 0x01f5" (to force this particular ECM PID)
PID 0x01f5 is correct but for some reason tsdecrypt fails to send this PID and then switches to 0x02bd
> 
> 2018-04-18 18:27:43 | --- | ECM pid : 0x02bd (VIACCESS) (forced: 0x01f5)
> 2018-04-18 18:27:43 | --- | ECM pid : 0x01f5 (VIACCESS) idx:0
> 2018-04-18 18:27:43 | --- | ECM pid : 0x02bd (VIACCESS) idx:1
> 2018-04-18 18:27:43 | NEW | Input PID 0x0065 appeared (PMT)
> 2018-04-18 18:27:43 | NEW | Input PID 0x00c9 appeared (H.264/14496-10 video (MPEG-4/AVC))
> 2018-04-18 18:27:43 | NEW | Input PID 0x0191 appeared (13818-3 audio (MPEG-2))
> 2018-04-18 18:27:43 | NEW | Input PID 0x012d appeared (13818-3 audio (MPEG-2))
> 2018-04-18 18:27:43 | NEW | Input PID 0x0259 appeared (H.222.0/13818-1 PES private data)
> 2018-04-18 18:27:43 | SDT | Service 0x1005 ( 4101) Type: 0x01 (Tv) Provider: "GLOBECAST" Service: "6 TER"
> 2018-04-18 18:27:43 | NEW | Input PID 0x0011 appeared (SDT)
> 2018-04-18 18:27:43 | NEW | Input PID 0x01f5 appeared (ECM)
> 2018-04-18 18:27:43 | NEW | Input PID 0x0014 appeared (TDT/TOT)
> 2018-04-18 18:27:43 | NEW | Input PID 0x0012 appeared (EPG)
> 2018-04-18 18:27:43 | NEW | Input PID 0x0010 appeared (NIT)
> 2018-04-18 18:27:43 | ECC | SID 0x1005 ------------ EcmChng:     0 ms
> 2018-04-18 18:27:43 | ECM | SID 0x1005 CAID: 0x0500 PID 0x01f5 Table: 0x81 Length:  188 Data: 81 70 b9 00 80 29 90 07 04 14 00 08 06 0a 00 ..
> 2018-04-18 18:27:43 | ERR | [newcamd] Card was not able to decode the channel.
> 2018-04-18 18:27:43 | ECM | Switching ECM pid to 0x02bd (701) idx:1
> 2018-04-18 18:27:43 | ECC | SID 0x1005 ------------ EcmChng:   141 ms
> 2018-04-18 18:27:43 | ECM | SID 0x1005 CAID: 0x0500 PID 0x01f5 Table: 0x80 Length:  188 Data: 80 70 b9 00 80 29 90 07 04 14 00 08 06 0a 00 ..
> 2018-04-18 18:27:43 | NEW | Input PID 0x02bd appeared (ECM)
> 2018-04-18 18:27:43 | ERR | [newcamd] Card was not able to decode the channel.
> 

I have verified from other sources that the correct ECM pid is 0x01f5 however for some reason tsdecrypt doesnt send this ECM and switches to the next, "Switching ECM pid to 0x02bd (701) idx:1"

**Comment by gfto** [comment]
If you are forcing a pid, remove --ca-system VIACCESS. Choosing ca-system does not work along with pid forcing.

**Comment by barhom** [comment]
I will try to do this again but afaik --ca-system is ignored anyway when you are forcing a pid.
The issue here was that for some reason tsdecrypt was not sending the ECM at all.

I will try again and let you know.
