### ISSUE TITLE
empty output

### ISSUE THREAD

**Issue by spein46** [gfto/tsdecrypt#15]
Hi, when i try to decrypt ts source with tsdecrypt --const-cw 0x00000000000000001111111111111111 \
       --input encrypted-file.ts --output file://decrypted-file.ts command the output file is always empty.
Why?
thanks

**Comment by gfto** [comment]
Use  -3 --output-enc-pass       | Output the stream even if can not be decrypted.

**Comment by spein46** [comment]
<img width="1440" alt="schermata 2018-05-22 alle 18 43 14" src="https://user-images.githubusercontent.com/17325529/40377064-3b8da108-5df0-11e8-9a03-9b958fb55cba.png">

This is output, the destination file is 0 byte, this is the screen of input file hex:
<img width="869" alt="schermata 2018-05-22 alle 18 46 09" src="https://user-images.githubusercontent.com/17325529/40377134-6f488058-5df0-11e8-8ade-1f1b99e09185.png">
